repos:
  - repo: local
    hooks:
      - id: update-version
        name: Update version number
        entry: bash -c 'echo $(($(git rev-list --count HEAD) + 1)) > VERSION && git add VERSION'
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

      - id: make-fix
        name: Format and fix code
        entry: make fix
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

